name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    name: Publish release
    if: github.repository_owner == 'codeismyid'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            bun.sh:443
            fulcio.sigstore.dev:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            uploads.github.com:443

      - name: Git checkout (full-history)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up bun@latest
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Install dependencies
        run: bun ci

      - name: Run check
        run: bun check

      - name: Audit signatures
        run: npm audit signatures

      - name: Build dist
        run: bun dist

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun release
